-- Seed initial plans
-- This migration inserts the 4 base plans: Free, Starter, Professional, Enterprise

-- Insert plans (idempotent - only if they don't exist)
INSERT INTO "plans" (
    "id",
    "slug",
    "name",
    "description",
    "price",
    "yearly_price",
    "limits",
    "features",
    "is_active",
    "sort_order",
    "created_at",
    "updated_at"
)
SELECT
    gen_random_uuid(),
    'free',
    'Free',
    'Para começar seu negócio',
    0,
    0,
    '{"maxUsers": 1, "maxCustomers": 20, "maxOrders": 10, "maxStorage": 500}'::jsonb,
    '{
        "customers": true,
        "services": true,
        "quotations": true,
        "orders": true,
        "schedule": true,
        "basic_financial": true,
        "reports_excel": true,
        "portal_client": false,
        "whatsapp": false,
        "email_automation": false,
        "nfe": false,
        "api": false,
        "custom_fields": false
    }'::jsonb,
    true,
    1,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM "plans" WHERE "slug" = 'free');

INSERT INTO "plans" (
    "id",
    "slug",
    "name",
    "description",
    "price",
    "yearly_price",
    "limits",
    "features",
    "is_active",
    "sort_order",
    "created_at",
    "updated_at"
)
SELECT
    gen_random_uuid(),
    'starter',
    'Starter',
    'Para profissionalizar seu atendimento',
    49.90,
    479.00,
    '{"maxUsers": 3, "maxCustomers": 100, "maxOrders": 50, "maxStorage": 5120}'::jsonb,
    '{
        "customers": true,
        "services": true,
        "quotations": true,
        "orders": true,
        "schedule": true,
        "basic_financial": true,
        "reports_excel": true,
        "portal_client": true,
        "whatsapp": true,
        "email_automation": true,
        "recurring_contracts": true,
        "custom_fields": true,
        "reports_pdf": true,
        "backup_auto": true,
        "nfe": false,
        "payment_gateway": false,
        "api": false
    }'::jsonb,
    true,
    2,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM "plans" WHERE "slug" = 'starter');

INSERT INTO "plans" (
    "id",
    "slug",
    "name",
    "description",
    "price",
    "yearly_price",
    "limits",
    "features",
    "is_active",
    "sort_order",
    "created_at",
    "updated_at"
)
SELECT
    gen_random_uuid(),
    'professional',
    'Professional',
    'Para empresas em crescimento',
    99.90,
    959.00,
    '{"maxUsers": 10, "maxCustomers": 500, "maxOrders": 300, "maxStorage": 51200}'::jsonb,
    '{
        "customers": true,
        "services": true,
        "quotations": true,
        "orders": true,
        "schedule": true,
        "basic_financial": true,
        "reports_excel": true,
        "portal_client": true,
        "whatsapp": true,
        "email_automation": true,
        "recurring_contracts": true,
        "custom_fields": true,
        "reports_pdf": true,
        "backup_auto": true,
        "nfe": true,
        "payment_gateway": true,
        "inventory": true,
        "profitability_reports": true,
        "multi_company": true,
        "granular_permissions": true,
        "online_scheduling": true,
        "webhooks": true,
        "api_full": false,
        "whitelabel": false
    }'::jsonb,
    true,
    3,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM "plans" WHERE "slug" = 'professional');

INSERT INTO "plans" (
    "id",
    "slug",
    "name",
    "description",
    "price",
    "yearly_price",
    "limits",
    "features",
    "is_active",
    "sort_order",
    "created_at",
    "updated_at"
)
SELECT
    gen_random_uuid(),
    'enterprise',
    'Enterprise',
    'Para grandes operações',
    299.90,
    2879.00,
    '{"maxUsers": -1, "maxCustomers": -1, "maxOrders": -1, "maxStorage": 204800}'::jsonb,
    '{
        "customers": true,
        "services": true,
        "quotations": true,
        "orders": true,
        "schedule": true,
        "basic_financial": true,
        "reports_excel": true,
        "portal_client": true,
        "whatsapp": true,
        "email_automation": true,
        "recurring_contracts": true,
        "custom_fields": true,
        "reports_pdf": true,
        "backup_auto": true,
        "nfe": true,
        "payment_gateway": true,
        "inventory": true,
        "profitability_reports": true,
        "multi_company": true,
        "granular_permissions": true,
        "online_scheduling": true,
        "webhooks": true,
        "api_full": true,
        "whitelabel": true,
        "bi_dashboard": true,
        "sla_99_9": true,
        "dedicated_support": true,
        "onboarding": true,
        "training": true,
        "priority_roadmap": true
    }'::jsonb,
    true,
    4,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM "plans" WHERE "slug" = 'enterprise');
